### ISSUE TITLE
VSCode plugin breaks backwards search in terminal

### ISSUE THREAD

**Issue by jplatte** [willcrichton/flowistry#61]
Because the extension registers *Ctrl+R something* as a keyboard shortcut that is active even when the terminal is focused, Ctrl+R is no longer passed to the terminal when the extension is installed. Could you please constrain the shortcut to when the editor is focused, or sth. similar? I can also send a PR if you can tell me where the default keybindings are located.

**Comment by willcrichton** [comment]
The keybindings are defined in the package.json of the IDE extension: https://github.com/willcrichton/flowistry/blob/master/ide/package.json#L84-L105

You can setup the VSCode extension by doing `npm install && npm run build` in the `ide` directory. Then you symlink the `ide` directory into `$HOME/.vscode/extensions` and delete the plugin installed from the marketplace. 

Feel free to mess with the keybindings and see what make sense. Otherwise I can get to this later.
